from __future__ import annotations

from pathlib import Path

import pytest

from dns2bgp_resolver.application.services.domain_index_service import DomainIndexService
from dns2bgp_resolver.application.services.ipv6_policy import ModeBasedIpv6Policy
from dns2bgp_resolver.config import Ipv6Settings
from dns2bgp_resolver.domain import Domain
from dns2bgp_resolver.domain.domain_index import DomainIndex
from dns2bgp_resolver.infrastructure.db.sqlite_repository import SqlAlchemyDomainRepository
from dns2bgp_resolver.infrastructure.dnsdist.domain_list_exporter import DnsdistDomainListExporter


@pytest.fixture
async def repo(tmp_path: Path):
    repository = SqlAlchemyDomainRepository(f"sqlite+aiosqlite:///{tmp_path / 't.db'}")
    await repository.initialize()
    yield repository
    await repository.close()


def test_names_snapshot():
    idx = DomainIndex()
    idx.rebuild(rules=[("exact.com", "exact"), ("suffix.com", "suffix")])
    assert idx.names_snapshot() == frozenset({"exact.com", "suffix.com"})


@pytest.mark.asyncio
async def test_dnsdist_exporter_writes_sorted(tmp_path: Path):
    path = tmp_path / "aaaa-suppress.domains"
    settings = Ipv6Settings(
        mode="suppress",
        dnsdist_list_path=str(path),
        dnsdist_reload_enable=False,
    )
    exporter = DnsdistDomainListExporter(settings)
    await exporter.export({"zeta.test", "alpha.test"})
    text = path.read_text(encoding="utf-8")
    assert "# generated by dns2bgp-resolver" in text
    lines = [ln for ln in text.splitlines() if ln and not ln.startswith("#")]
    assert lines == ["alpha.test", "zeta.test"]


@pytest.mark.asyncio
async def test_policy_off_noop(tmp_path: Path):
    path = tmp_path / "aaaa-suppress.domains"
    settings = Ipv6Settings(mode="off", dnsdist_list_path=str(path))
    policy = ModeBasedIpv6Policy(settings)
    idx = DomainIndex()
    idx.rebuild({"example.com"})
    await policy.apply(idx)
    assert not path.exists()


@pytest.mark.asyncio
async def test_policy_suppress_exports(tmp_path: Path):
    path = tmp_path / "aaaa-suppress.domains"
    settings = Ipv6Settings(
        mode="suppress",
        dnsdist_list_path=str(path),
        dnsdist_reload_enable=False,
    )
    policy = ModeBasedIpv6Policy(settings)
    idx = DomainIndex()
    idx.rebuild(rules=[("youtube.com", "suffix")])
    await policy.apply(idx)
    assert "youtube.com" in path.read_text(encoding="utf-8")


@pytest.mark.asyncio
async def test_policy_announce_stub_no_file(tmp_path: Path, caplog: pytest.LogCaptureFixture):
    path = tmp_path / "aaaa-suppress.domains"
    settings = Ipv6Settings(mode="announce", dnsdist_list_path=str(path))
    policy = ModeBasedIpv6Policy(settings)
    idx = DomainIndex()
    idx.rebuild({"example.com"})
    with caplog.at_level("INFO"):
        await policy.apply(idx)
    assert not path.exists()
    assert any("announce is not implemented" in r.message for r in caplog.records)


@pytest.mark.asyncio
async def test_rebuild_triggers_suppress(repo, tmp_path: Path):
    path = tmp_path / "list.domains"
    settings = Ipv6Settings(
        mode="suppress",
        dnsdist_list_path=str(path),
        dnsdist_reload_enable=False,
    )
    policy = ModeBasedIpv6Policy(settings)
    idx = DomainIndex()
    svc = DomainIndexService(repo, idx, ipv6_policy=policy)
    await repo.add(Domain.create("manual.test", source="manual"))
    size = await svc.rebuild()
    assert size == 1
    assert "manual.test" in path.read_text(encoding="utf-8")


@pytest.mark.asyncio
async def test_rebuild_off_skips_export(repo, tmp_path: Path):
    path = tmp_path / "list.domains"
    settings = Ipv6Settings(mode="off", dnsdist_list_path=str(path))
    policy = ModeBasedIpv6Policy(settings)
    idx = DomainIndex()
    svc = DomainIndexService(repo, idx, ipv6_policy=policy)
    await repo.add(Domain.create("manual.test", source="manual"))
    await svc.rebuild()
    assert not path.exists()


@pytest.mark.asyncio
async def test_reload_failure_does_not_raise(tmp_path: Path):
    path = tmp_path / "aaaa-suppress.domains"
    settings = Ipv6Settings(
        mode="suppress",
        dnsdist_list_path=str(path),
        dnsdist_reload_enable=True,
        dnsdist_reload_cmd=["/nonexistent/dnsdist-binary", "-c", "reload"],
    )
    exporter = DnsdistDomainListExporter(settings)
    await exporter.export({"example.com"})
    assert path.exists()
