# Fragment to include from bird.conf
#
#   include "/etc/bird/dns2bgp.include.conf";
#
# And set dns2bgp config:
#   bird.include_path: /var/lib/dns2bgp/dns2bgp.routes
#
# Then in bird.conf (or this fragment), pull in the generated routes:

include "/var/lib/dns2bgp/dns2bgp.routes";
