from __future__ import annotations

import asyncio
import logging
import os
import tempfile
from pathlib import Path

from dns2bgp_resolver.config import Ipv6Settings

logger = logging.getLogger(__name__)


class DnsdistDomainListExporter:
    """
    Atomic write of DomainIndex names for dnsdist SuffixMatchNode.

    dnsdist reload is best-effort and never fails the export.
    """

    def __init__(self, settings: Ipv6Settings) -> None:
        self._settings = settings

    def _render(self, names: frozenset[str] | set[str]) -> str:
        lines = [
            "# generated by dns2bgp-resolver — do not edit",
            "# one domain per line; load into dnsdist SuffixMatchNode",
        ]
        lines.extend(sorted(names))
        lines.append("")
        return "\n".join(lines)

    async def export(self, names: frozenset[str] | set[str]) -> None:
        path = Path(self._settings.dnsdist_list_path)
        content = self._render(names)
        await asyncio.to_thread(self._atomic_write, path, content)
        logger.info("wrote %d domain(s) to %s", len(names), path)
        if self._settings.dnsdist_reload_enable:
            await self._reload_dnsdist()

    @staticmethod
    def _atomic_write(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        os.chmod(path.parent, 0o755)
        fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp_name, path)
            os.chmod(path, 0o664)
        except Exception:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise

    async def _reload_dnsdist(self) -> None:
        cmd = self._settings.dnsdist_reload_cmd
        if not cmd:
            logger.warning("dnsdist reload enabled but dnsdist_reload_cmd is empty")
            return
        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await proc.communicate()
            if proc.returncode != 0:
                logger.warning(
                    "dnsdist reload failed (rc=%s): %s %s",
                    proc.returncode,
                    stdout.decode(errors="replace"),
                    stderr.decode(errors="replace"),
                )
            else:
                logger.info("dnsdist reload ok")
        except FileNotFoundError:
            logger.warning("dnsdist reload binary not found: %s", cmd[0])
        except Exception as exc:  # noqa: BLE001
            logger.warning("dnsdist reload error: %s", exc)
