from __future__ import annotations

import asyncio
import logging
import os
import re
import tempfile
from pathlib import Path

from dns2bgp_resolver.application.ports.route_exporter import RouteExporter
from dns2bgp_resolver.config import BirdSettings

logger = logging.getLogger(__name__)

_ROUTE_LINE = re.compile(r"^\s*route\s+\S+")
_COUNT_RE = re.compile(r"(\d+)\s+of\s+(\d+)|Total:\s*(\d+)|^(\d+)\s*$", re.I | re.M)


def _looks_like_ip(value: str) -> bool:
    parts = value.split(".")
    if len(parts) != 4:
        return False
    try:
        return all(0 <= int(p) <= 255 for p in parts)
    except ValueError:
        return False


def count_routes_in_file(path: str | Path) -> int | None:
    try:
        text = Path(path).read_text(encoding="utf-8")
    except OSError:
        return None
    return sum(1 for line in text.splitlines() if _ROUTE_LINE.match(line))


def _parse_bird_count(output: str) -> int | None:
    matches = list(_COUNT_RE.finditer(output))
    if not matches:
        # Fallback: count route lines in show route output
        n = sum(1 for line in output.splitlines() if _ROUTE_LINE.match(line) or "/" in line and "unicast" in line.lower())
        return n if n else None
    last = matches[-1]
    for g in last.groups():
        if g is not None:
            return int(g)
    return None


async def query_bird_route_count(settings: BirdSettings) -> int | None:
    cmd = [settings.birdc_bin]
    if settings.birdc_socket:
        cmd.extend(["-s", settings.birdc_socket])
    cmd.extend(["show", "route", "protocol", settings.protocol_name, "count"])
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode != 0:
            logger.debug(
                "birdc route count failed: %s %s",
                stdout.decode(errors="replace"),
                stderr.decode(errors="replace"),
            )
            return None
        return _parse_bird_count(stdout.decode(errors="replace"))
    except FileNotFoundError:
        return None
    except Exception:  # noqa: BLE001
        logger.debug("birdc route count error", exc_info=True)
        return None


class StaticFileBirdExporter(RouteExporter):
    """
    Write an include file bird can load independently of this process.

    Atomic replace keeps bird readable even if the writer crashes mid-write.
    birdc reload is best-effort and never fails the export.
    """

    def __init__(self, settings: BirdSettings) -> None:
        self._settings = settings

    def _via_clause(self) -> str:
        nexthop = self._settings.nexthop
        if _looks_like_ip(nexthop):
            return f"via {nexthop}"
        return f'via "{nexthop}"'

    def _render(self, prefixes: list[str]) -> str:
        via = self._via_clause()
        lines = [
            "# generated by dns2bgp-resolver — do not edit",
            f"protocol static {self._settings.protocol_name} {{",
#            f"  ipv4 {{ table {self._settings.table}; }};",
            f"  ipv4;",
        ]
        for prefix in prefixes:
#            lines.append(f"  route {prefix} {via};")
            lines.append(f"  route {prefix} reject;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    async def export(self, prefixes: list[str]) -> None:
        path = Path(self._settings.include_path)
        content = self._render(prefixes)
        await asyncio.to_thread(self._atomic_write, path, content)
        logger.info("wrote %d route(s) to %s", len(prefixes), path)
        if self._settings.birdc_enable:
            await self._reload_bird()

    @staticmethod
    def _atomic_write(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        os.chmod(path.parent, 0o755)
        fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp_name, path)
            os.chmod(path, 0o664)
        except Exception:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise

    def _birdc_cmd(self, *args: str) -> list[str]:
        cmd = [self._settings.birdc_bin]
        if self._settings.birdc_socket:
            cmd.extend(["-s", self._settings.birdc_socket])
        cmd.extend(args)
        return cmd

    async def _reload_bird(self) -> None:
        try:
            proc = await asyncio.create_subprocess_exec(
                *self._birdc_cmd("configure"),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await proc.communicate()
            if proc.returncode != 0:
                logger.warning(
                    "birdc configure failed (rc=%s): %s %s",
                    proc.returncode,
                    stdout.decode(errors="replace"),
                    stderr.decode(errors="replace"),
                )
            else:
                logger.info("birdc configure ok")
        except FileNotFoundError:
            logger.warning("birdc binary not found: %s", self._settings.birdc_bin)
        except Exception as exc:  # noqa: BLE001
            logger.warning("birdc configure error: %s", exc)
